### PR TITLE
ZBOSS adapter for nRF ZBOSS NCP

### PR DESCRIPTION
**Pull request by kirovilya**
The beta version of the ZBOSS adapter for [nRF ZBOSS NCP](https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/samples/zigbee/ncp/README.html). 

Based on the [zigpy-zboss library code](https://github.com/kardia-as/zigpy-zboss)

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you also make a PR for zigbee2mqtt.io?

Note to self; after this merge https://github.com/Koenkk/zigbee2mqtt/pull/23747

**Comment by kirovilya** [comment]
> Could you also make a PR for zigbee2mqtt.io?

Yes, I will try

**Comment by kirovilya** [comment]
but later... Not today and not tomorrow

**Comment by kirovilya** [comment]
> today

done :)

**Pull request merged**
