### PR TITLE
Touchlink

### PR DESCRIPTION
**Pull request by Koenkk**

### CODE REVIEW

**Comment by sjorge** [comment]
What spec are you basing this off? I googled a bit and it seems to be part of ZLL but did not find much details of how it is implemented.

**Comment by Koenkk** [comment]
It is implemented through a combination of cluster commands and interpan communication, documentation is indeed not very good. I reverse engineered most of the things atm.

**Comment by sjorge** [comment]
OK so it wasn't just my google foo failing me then, good luck

**Comment by Sineos** [comment]
Interesting reading material:
[wisec2017_touchlink.pdf](https://github.com/Koenkk/zigbee-herdsman/files/3863141/wisec2017_touchlink.pdf)

**Pull request merged**
