### PR TITLE
Ember: fix GP proxied messages handling.

### PR DESCRIPTION
**Pull request by Nerivec**
Fixes https://github.com/Koenkk/zigbee2mqtt/issues/23575
Also needs testing against https://github.com/Koenkk/zigbee-herdsman/issues/823 and https://github.com/Koenkk/zigbee2mqtt/issues/20586 to confirm if fixed.

CC: @chris-1243 @dduransseau

### CODE REVIEW

**Comment by chris-1243** [comment]
@Nerivec 

I just had some tries on a test network. I had to disassemble the antenna from my Dongle-E in order to reduce drastically its coverage. I added an Ikea router close to it and then far from the light, I have been able to pair a PTM215ZE through this light. For me, it is fixed.

I also tried at the same emplacement to pair the PTM directly to the coordinator without success.

[log_debug.txt](https://github.com/user-attachments/files/16663478/log_debug.txt)
[log_info.txt](https://github.com/user-attachments/files/16663479/log_info.txt)

**Comment by 0BanZai0** [comment]
Hi guys, I have the exact same issue with my hue bulbs and ZGP switches. 
Great to see, that there is a fix for it, but how can I install it?
The prod an dev releases of Z2M don't seem to include this fix... sorry for being new here :)

**Comment by 0BanZai0** [comment]
Hi guys, I have the exact same issue with my hue bulbs and ZGP switches. 
Great to see, that there is a fix for it, but how can I install it?
The prod an dev releases of Z2M don't seem to include this fix... sorry for being new here :)

**Comment by Koenkk** [comment]
@0BanZai0 it's included in the dev release.

**Comment by 0BanZai0** [comment]
@Koenkk - thanks. For what I've understood is that I have to install the "Edge" version of Z2M via the HASS Addon Store. Correct?
Do I have to uninstall the prod version first?
Can I keep all my devices and settings?

**Comment by Koenkk** [comment]
You can just uninstall and install edge, all data is preserved.

**Comment by 0BanZai0** [comment]
@Koenkk THANKS!
I've just backed up all my config files from the prod version. Stopped it and installed the edge version. There I've pasted my serial config and hit "start". Seems to work :)
All my devices are there - should be like this as prod and edge share the same config directory!

**Comment by 0BanZai0** [comment]
@Koenkk 

One last question. I can confirm that I'm on the newest version:

Zigbee2MQTT-Version
1.39.1-dev commit: [b92072f](https://github.com/Koenkk/zigbee2mqtt/commit/b92072f)

Coordinator-Typ
EmberZNet

Coordinator-Version
7.4.3 [GA]

Coordinator IEEE Adresse
0xe0798dfffec05838

Frontend-Version
0.7.4

Zigbee Herdsman Konverter Version
20.3.0

Zigbee Herdsman Version
0.56.2

But my Philips Hue GU10 and E27 bulb still is only showing "greenPower" as an output-cluster on endpoint 242.

image

In this thread they had the same behavior:
 https://github.com/Koenkk/zigbee2mqtt/issues/20586#issuecomment-2119296257

Is this just a visual thing?

**Comment by chris-1243** [comment]
I would suggest to check the documentation regarding [ZGP](https://www.zigbee2mqtt.io/advanced/zigbee/01_zigbee_network.html#green-power-devices). 

> But my Philips Hue GU10 and E27 bulb still is only showing "greenPower" as an output-cluster on endpoint 242.

Your picture shows only the clusters and there is nothing Z2M can do here as it is firmware related.

**Comment by 0BanZai0** [comment]
@chris-1243 - thanks! I'll try it in my new home tomorrow. Should work as a lot of my lights are these: https://www.zigbee2mqtt.io/devices/929001953301.html

According to your provided documentation they should act as a Proxy and support Unicast. 
I'll try to connect the GP switches to the nearest light.

**Comment by chris-1243** [comment]
> I'll try to connect the GP switches to the nearest light.

What is really important is to select a specific router while pairing your ZGP switch. Otherwise, it will be paired as `broadcast` and your network might start to act slowly if you have lots of them.

**Comment by 0BanZai0** [comment]
> > I'll try to connect the GP switches to the nearest light.
> 
> 
> 
> What is really important is to select a specific router while pairing your ZGP switch. Otherwise, it will be paired as `broadcast` and your network might start to act slowly if you have lots of them.

@chris-1243 
I've reconnected all my switches today by just allowing them to join via the nearest hue bulb. This seems to have solved the LQI / range issue.
But now I'm getting a lot of "Network Busy" errors when pressing the buttons too fast repeatedly.

The errors look like this:

"z2m: Publish 'set' 'state' to 'Spots
Wohnzimmer' failed: 'Error: Command 5 genOnOff.on (}) failed (~x~> [ZCL GROUP] Failed to send with status=BUSY.)'"

I'm using z2m groups to group my bulbs in a specific room.

I'm thinking about switching to channel 25 and to re-pair everything... 

What do you think might be a solution here ?

**Comment by chris-1243** [comment]
> I'm thinking about switching to channel 25 and to re-pair everything...

As you are on `ember`, there is no need to re-pair everything. Only your ZGP device if you are using PTM21xZ/ZE will have to.

By the way, what kind of ZGP switch are you using? On my small test network, everything went fine, no errors to report.

Could you provide debug log? Maybe @Nerivec could find something in it.

**Comment by Nerivec** [comment]
BUSY on group/broadcast messages means you likely hit the broadcast flood prevention system (ZigBee specification). It triggers at about 8 broadcasts per 9-second window to prevent storming the network. There are some queueing mechanisms in place, but it looks like your network burns through them too.
Like Chris said, check your logs, see what is triggering so many multicasts/broadcasts.

**Comment by 0BanZai0** [comment]
@chris-1243 @Nerivec 
Thank you both for your support.
I'm having 20 mains powered PTM 215Z switches from "LED-Trading".

I'll try to fetch a log this evening when I'm back at the new house!

**Comment by chris-1243** [comment]
Is this model battery powered ? I am just wondering if its sends the same frame as the non-powered model and the exact same commands. Do you have the possibility to sniff your traffic ?

**Comment by chris-1243** [comment]
Well, [here](https://www.zigbee2mqtt.io/devices/PTM_215Z.html) you will get a link of a PTM215Z.

What you provided is effectively a ZGP device but not a PTM21xZ/ZE.

I would suggest to open a new issue regarding your device and not continue here as, for me, it is not related to the fix @Nerivec provived.

**Comment by chris-1243** [comment]
@0BanZai0 You may check this open issue which talks about unicast/broadcast message as well as which router performs well with ZGP devices....

https://github.com/Koenkk/zigbee2mqtt/issues/22897

**Pull request merged**
