### PR TITLE
introduce Endpoint.binds property

### PR DESCRIPTION
**Pull request by hobbyquaker**

### CODE REVIEW

**Comment by hobbyquaker** [comment]
I think we need a save() after adding members to the bind array, but I have no clue how to trigger that in endpoint.ts, do I have access to Controller.getDeviceByIeeeAddr() there?

**Comment by Koenkk** [comment]
Thanks! (will fix tests later)

**Comment by hobbyquaker** [comment]
Cool, thanks! Looks much cleaner then my approach, looking at the diffs is a good training for me :)

**Comment by hobbyquaker** [comment]
Question for my understanding: isn't it necessary to explicitly call Device.save() after a bind is done?

**Comment by Koenkk** [comment]
@hobbyquaker you are too fast; will push that soon.

Note to zigbee-herdsman 0.8.0 will have breaking changes, I will add them to README.md

**Comment by hobbyquaker** [comment]
I‘m right now preparing another PR: get rid of jsdoc, use typedoc. much better. direct code coupling, no efforts anymore for creating api docs, no doc comments needed...

**Comment by Koenkk** [comment]
Ok great! Then the only thing we would need to do is add proper comments to each function?

**Comment by hobbyquaker** [comment]
Exactly. All Params/Returns/Fulfils/Interfaces/Types will be autogenerated.

**Comment by Koenkk** [comment]
Awesome!

**Comment by hobbyquaker** [comment]
Yeah :) Leads to the question: why didn't I google "typescript jsdoc" before starting the docs ;-)

**Pull request merged**
