### PR TITLE
Sinope fs4220

### PR DESCRIPTION
**Pull request by mdallaire**
Add cluster for the optional flow meter (FS4220) configuration of the Sinope VA4220ZB G2.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by KalenWessel** [comment]
Sorry to bump an older PR but @mdallaire is there something I'm missing when trying to write in a new flowMeterConfig?

I'm attempting to enable my FS4220 flow meter.

```
zigbee2mqtt/0x500b91400003ecc3/set/write
{"cluster": "manuSpecificSinope", "payload": {"flowMeterConfig": [194,17,0,0,136,119,0,0,1,0,0,0]}} # I'm getting the array values from https://github.com/claudegel/sinope-zha 
```

```
z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'write' to '0x500b91400003ecc3' failed: 'TypeError: ZCL command 0x500b91400003ecc3/1 manuSpecificSinope.write({\"flowMeterConfig\":[194,17,0,0,136,119,0,0,1,0,0,0]}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4508,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Cannot read properties of undefined (reading 'length'))'","meta":{"friendly_name":"0x500b91400003ecc3"},"type":"zigbee_publish_error"}'
```

**Comment by pfak** [comment]
I also have the same issue @KalenWessel, is the DataType array not properly parsed by zigee2mqtt?

```
{
  "write": {
    "cluster": "manuSpecificSinope",
    "payload": {
       "flowMeterConfig": [32, 12, 0, 159, 38, 0, 0, 76, 85, 1, 0, 1, 0, 0, 0]
    }
  }
}
```

Returns:

```
z2m: Publish 'set' 'write' to 'Water valve' failed: 'TypeError: ZCL command 0x500b914000050b43/1 manuSpecificSinope.write({"flowMeterConfig":[32,12,0,159,38,0,0,76,85,1,0,1,0,0,0]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"manufacturerCode":4508,"writeUndiv":false}) failed (Cannot read properties of undefined (reading 'length'))'
```

**Comment by Nerivec** [comment]
It should be something like this for arrays:

```json
{
  "write": {
    "cluster": "manuSpecificSinope",
    "payload": {
       "flowMeterConfig": {
         "elementType": "UINT8",
         "elements": [32, 12, 0, 159, 38, 0, 0, 76, 85, 1, 0, 1, 0, 0, 0]
       }
    }
  }
}
```

Note: the [linked repo](https://github.com/claudegel/sinope-zha) indicates it expects 12 elements though?

**Comment by pfak** [comment]
Wow  @Nerivec ! This works:

```
{
  "write": {
    "cluster": "manuSpecificSinope",
    "payload": {
       "flowMeterConfig": {
"elementType": "UINT8",
"elements": [32, 12, 0, 159, 38, 0, 0, 76, 85, 1, 0, 1]

}
    }
  }
}
```

Where the heck is this documented??

**Comment by Nerivec** [comment]
I read the code 😁
https://github.com/Koenkk/zigbee-herdsman/blob/2da206da4b4376c22b192d4d15a6e4bef389e996/src/zspec/zcl/definition/tstype.ts#L16-L19
Not sure it's documented beyond that. This stuff is supposed to be abstracted behind exposes, but looks like this device is lacking a bit in that area.

**Comment by pfak** [comment]
Very lacking. I appreciate you diving in! I looked everywhere for hours :)

Now I need to figure out how to actually see the flow. I was following the ZHA quirks someone wrote:

https://github.com/claudegel/sinope-zha

**Comment by Nerivec** [comment]
From that link, looks like it's `msFlowMeasurement` with attribute ID 0 (`measuredValue`):
https://github.com/Koenkk/zigbee-herdsman/blob/2da206da4b4376c22b192d4d15a6e4bef389e996/src/zspec/zcl/definition/cluster.ts#L2485-L2495
Or maybe via `seMetering` with attribute ID 0 (`currentSummDelivered`), that one is already in the converter.
I don't know that device, so, not sure which does what exactly.

Someone with that device should take a look at improving the converter in ZHC 😉
https://github.com/Koenkk/zigbee-herdsman-converters/blob/ed574c7387223b2cb9201f004c01c6dd3ecd0fea/src/devices/sinope.ts#L1665-L1692

**Comment by pfak** [comment]
It's a water valve that can turn the water on/off, leak detect and also show flow.

**Comment by pfak** [comment]
I'm trying to learn how this all plugs together and then I'll submit a PR .. mgiht be awhile :)

**Pull request merged**
