### PR TITLE
EZSP: parsing frame 0x00C4 - multiple cases

### PR DESCRIPTION
**Pull request by kirovilya**
A curious situation is the processing of two different frames with the same code.
changeSourceRouteHandler and incomingNetworkStatusHandler have one code 0x00C4

based on https://github.com/Koenkk/zigbee-herdsman/pull/640 and related to https://github.com/Koenkk/zigbee2mqtt/issues/15724

### CODE REVIEW

**Comment by MattWestb** [comment]
I think its the first have being deleted and the new one shall being in V10 of the protocol but is not documented in the last release notes..

**Comment by kirovilya** [comment]
@MattWestb  we will have to support old frames as long as there are users with old firmware (not v10) :)

**Comment by Hedda** [comment]
> I think its the first have being deleted and the new one shall being in V10 of the protocol but is not documented in the last release notes

@kirovilya  For reference also see the post about EZSP v10 in https://github.com/Koenkk/zigbee-herdsman/issues/319#issuecomment-1431093193

> @kirovilya FYI, read someone noticed that EZSP protocol version has been incremented to EZSP v10 in Gecko SDK v4.2 / Zigbee EmberZNet v7.2 and that EZSP v10 was not mentioned in the latest UG100 (EZSP Reference Guide) documentation from Silicon Labs which SiLabs only updated for EZSP v9 and state that no additions was added between EmberZNet PRO Release 7.1.1 and 7.2.0:
> 
> https://github.com/SiliconLabs/gecko_sdk/blob/gsdk_4.2/protocol/zigbee/app/util/ezsp/ezsp-protocol.h
> 
> https://www.silabs.com/documents/public/user-guides/ug100-ezsp-reference-guide.pdf)
> 
> Does it look like there are many differences between these protocol framing with additions or changes in EZSP v10? _The only major addition in EZSP v10 looks to be `incomingNetworkStatusHandler`, which was previously `changeSourceRouteHandler` so need to handle that it was renamed in that version of the protocol which is used by default in Silicon Labs Zigbee EmberZNet 7.2 firmware._
> 
> Gecko SDK v4.2:
> 
> * https://github.com/SiliconLabs/gecko_sdk/blob/gsdk_4.2/protocol/zigbee/app/util/ezsp/ezsp-protocol.h
> * EZSP_PROTOCOL_VERSION = 10
> 
> Gecko SDK v4.1:
> 
> * https://github.com/SiliconLabs/gecko_sdk/blob/gsdk_4.1/protocol/zigbee/app/util/ezsp/ezsp-protocol.h
> * EZSP_PROTOCOL_VERSION = 9
> 
> Gecko SDK v4.0:
> 
> * https://github.com/SiliconLabs/gecko_sdk/blob/gsdk_4.0/protocol/zigbee/app/util/ezsp/ezsp-protocol.h
> * EZSP_PROTOCOL_VERSION = 8
> 
> For reference, Nabu Casa is already officially offering downloads for both "stable" EmberZNet 7.1.x.x (EZSP v9) firmware images as well as "beta" EmberZNet 7.2.x.x (EZSP v10) firmware image for their recently released Home Assistant SkyConnect adapter/dongle/stick:
> 
> https://www.home-assistant.io/skyconnect/
> 
> https://github.com/NabuCasa/silabs-firmware/tree/main/EmberZNet
> 
> https://github.com/NabuCasa/silabs-firmware/tree/main/EmberZNet/beta
> 
> xsp1989 is also offering EmberZNet 7.1.x.x (EZSP v9) and EmberZNet 7.2.x.x (EZSP v10) firmware image builds for his ZB-GW04 USB stick (a.k.a. "easyiot Zigbee dongle") that he designed based on "SM-011 V1.x" (ZYZBP008) radio module from CoolKit-Technologies (which in turn has an EFR32MG21 SoC).
> 
> https://github.com/xsp1989/zigbeeFirmware/tree/master/firmware/Zigbee3.0_Dongle-NoSigned/EZSP
> 
> https://www.aliexpress.com/item/1005002791666029.html
> 
> PS: xsp1989's firmware images for ZB-GW04 are also compatible with Sonoff ZBDongle-E by ITead even though not optimized for it:
> 
> https://itead.cc/product/zigbee-3-0-usb-dongle/

**Comment by kirovilya** [comment]
> @kirovilya For reference also see the post about EZSP v10 in [#319 (comment)](https://github.com/Koenkk/zigbee-herdsman/issues/319#issuecomment-1431093193)

yes, I read

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
