### PR TITLE
Add Ikea VOC index cluster

### PR DESCRIPTION
**Pull request by 0ip**
Required by
https://github.com/Koenkk/zigbee-herdsman-converters/pull/5546

### CODE REVIEW

**Comment by sjorge** [comment]
Does this IKEA one also output a resolution value? The custom cluster used by Develco does and I think they are using the same sensirion sensors, you can check if it has an additional uint16 as attribute 3.

For reference:
https://github.com/Koenkk/zigbee-herdsman/blob/1644537c0366db7875c8b9176093e0733341dbfa/src/zcl/definition/cluster.ts#L4766-L4777

**Comment by 0ip** [comment]
@sjorge I have tested it and the attribute does not seem to be the present

**Comment by sjorge** [comment]
> @sjorge I have tested it and the attribute does not seem to be the present

Give your reply in the zhc PR, if this is a relative index like value it might makes sense there is none as it probably already accounts for some inaccuracies.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
