### PR TITLE
Use standard Zcl parser for green power frames

### PR DESCRIPTION
**Pull request by filips**
As far as I can tell, the Green Power Indication received should contain the full ZCL frame for the green power message. Thus, we could get a more correct and complete parsing of the contents by using the zcl parser. 

I have not tested this, as I do not have a Conbee II at my disposal.

Related issue: https://github.com/Koenkk/zigbee2mqtt/issues/12414

### CODE REVIEW

**Comment by Koenkk** [comment]
Getting this error:
```
(node:17210) UnhandledPromiseRejectionWarning: Error: Cluster 'greenPower' has no command response '0'
    at Object.getCommandResponse (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/zcl/utils.ts:135:19)
    at Function.fromBuffer (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/zcl/zclFrame.ts:179:72)
    at DeconzAdapter.checkReceivedGreenPowerIndication (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:1050:32)
    at EventEmitter.<anonymous> (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:78:87)
    at EventEmitter.emit (events.js:400:28)
    at parseGreenPowerDataIndication (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:313:23)
    at parseFrame (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:416:29)
    at processFrame (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:364:59)
    at Driver.<anonymous> (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:69:59)
    at Driver.emit (events.js:400:28)
(node:17210) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:17210) UnhandledPromiseRejectionWarning: Error: Cluster 'greenPower' has no command response '0'
    at Object.getCommandResponse (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/zcl/utils.ts:135:19)
    at Function.fromBuffer (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/zcl/zclFrame.ts:179:72)
    at DeconzAdapter.checkReceivedGreenPowerIndication (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:1050:32)
    at EventEmitter.<anonymous> (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:78:87)
    at EventEmitter.emit (events.js:400:28)
    at parseGreenPowerDataIndication (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:313:23)
    at parseFrame (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:416:29)
    at processFrame (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:364:59)
    at Driver.<anonymous> (/Users/koenkk/Git/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:69:59)
    at Driver.emit (events.js:400:28)
(node:17210) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

```

**Comment by Koenkk** [comment]
Better now but the device is not created yet.

1.25.0

```
  zigbee-herdsman:deconz:frameParser GP commissioning notification +8s
  zigbee-herdsman:deconz:frameParser GP_DATA_INDICATION - src id: 0x46f4fe cmd id: 0xe0 frameCounter: 0x75c +1ms
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":22,"manufacturerCode":null,"commandIdentifier":4},"Payload":{"options":62081,"srcID":4650238,"frameCounter":1884,"commandID":224,"payloadSize":27,"commandFrame":{"deviceID":2,"options":129,"extendedOptions":242,"securityKey":{"type":"Buffer","data":[241,236,146,171,255,143,19,99,225,70,190,181,24,201,12,171]},"keyMic":3587458724,"outgoingCounter":1884,"applicationInfo":0,"numGdpCommands":0,"gpdCommandIdList":{"type":"Buffer","data":[]}}},"Command":{"ID":4,"parameters":[{"name":"options","type":33},{"name":"srcID","type":35},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":2048}]},{"name":"gppGddLink","type":32,"conditions":[{"type":"bitMaskSet","param":"options","mask":2048}]}],"name":"commisioningNotification"}},"address":4650238,"endpoint":242,"linkquality":127,"groupID":2948,"wasBroadcast":false,"destinationEndpoint":1}' +18s
  zigbee-herdsman:controller:log 'zcl' data is from unknown device with address '4650238', skipping... +2ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 22 paramId: 1 +8s
  zigbee-herdsman:deconz:frameParser GP commissioning notification +6ms
  zigbee-herdsman:deconz:frameParser MAC: 0x00212effff04d4e0 +1ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 23 paramId: 7 +6ms
  zigbee-herdsman:deconz:frameParser NWKADDR: 0 +6ms
  zigbee-herdsman:deconz:adapter no response expected +15s
  zigbee-herdsman:controller:log Green power device '{"sourceID":4650238,"deviceID":2,"networkAddress":62718}' joined +9ms
  zigbee-herdsman:controller:log New green power device '0x000000000046f4fe' joined +0ms
  zigbee-herdsman:controller:log Creating device '0x000000000046f4fe' +0ms
Zigbee2MQTT:info  2022-05-10 19:55:51: Device '0x000000000046f4fe' joined
Zigbee2MQTT:info  2022-05-10 19:55:51: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000000000046f4fe","ieee_address":"0x000000000046f4fe"},"type":"device_joined"}'
Zigbee2MQTT:info  2022-05-10 19:55:51: Successfully interviewed '0x000000000046f4fe', device has successfully been paired
Zigbee2MQTT:info  2022-05-10 19:55:51: Device '0x000000000046f4fe' is supported, identified as: Philips Hue tap (8718696743133)
Zigbee2MQTT:info  2022-05-10 19:55:51: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Hue tap","exposes":[{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["press_1","press_2","press_3","press_4"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"8718696743133","options":[],"supports_ota":false,"vendor":"Philips"},"friendly_name":"0x000000000046f4fe","ieee_address":"0x000000000046f4fe","status":"successful","supported":true},"type":"device_interview"}'
  zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x EP:242 SeqNr. 24 request id: 4 +15ms
```


With these changes

```
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":18,"manufacturerCode":null,"commandIdentifier":0},"Payload":{"options":40,"srcID":4262199329,"frameCounter":3758114548,"commandID":2,"payloadSize":129,"commandFrame":{"raw":{"type":"Buffer","data":[242,241,236,146,171,255,143,19,99,225,70,190,181,24,201,12,171,164,70,212,213,112,7,0,0,153,238]}}},"Command":{"ID":0,"parameters":[{"name":"options","type":33},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGddLink","type":32,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}},"address":4262199329,"endpoint":242,"linkquality":127,"groupID":2948,"wasBroadcast":false,"destinationEndpoint":1}' +16s
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 18 paramId: 5 +6s
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":19,"manufacturerCode":null,"commandIdentifier":0},"Payload":{"options":40,"srcID":4262199329,"frameCounter":3758114548,"commandID":2,"payloadSize":129,"commandFrame":{"raw":{"type":"Buffer","data":[242,241,236,146,171,255,143,19,99,225,70,190,181,24,201,12,171,164,70,212,213,112,7,0,0,152,238]}}},"Command":{"ID":0,"parameters":[{"name":"options","type":33},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGddLink","type":32,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}},"address":4262199329,"endpoint":242,"linkquality":127,"groupID":2948,"wasBroadcast":false,"destinationEndpoint":1}' +3ms
  zigbee-herdsman:deconz:frameParser PANID: 1a62 +6s
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 19 paramId: 5 +6ms
  zigbee-herdsman:deconz:frameParser PANID: 1a62 +5ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 20 paramId: 11 +6ms
  zigbee-herdsman:deconz:frameParser APS_EXT_PANID: 0xdddddddddddddddd +6ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 21 paramId: 11 +6ms
  zigbee-herdsman:deconz:frameParser APS_EXT_PANID: 0xdddddddddddddddd +6ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 22 paramId: 28 +5ms
  zigbee-herdsman:deconz:frameParser CHANNEL: 15 +5ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 23 paramId: 28 +4ms
  zigbee-herdsman:deconz:frameParser CHANNEL: 15 +5ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 24 paramId: 24 +6ms
  zigbee-herdsman:deconz:frameParser NETWORK_KEY: hidden +5ms
  zigbee-herdsman:controller:greenpower Unhandled Zigbee GreenPower command: 0x2 +0ms
  zigbee-herdsman:controller:log 'zcl' data is from unknown device with address '4262199329', skipping... +32ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 25 paramId: 24 +5ms
  zigbee-herdsman:deconz:frameParser NETWORK_KEY: hidden +5ms
  zigbee-herdsman:controller:greenpower Unhandled Zigbee GreenPower command: 0x2 +5ms
  zigbee-herdsman:controller:log 'zcl' data is from unknown device with address '4262199329', skipping... +5ms
```

**Comment by filips** [comment]
I am a bit confused by the incoming data, so I've added a debug printout of the buffer.

**Comment by Koenkk** [comment]
```
  zigbee-herdsman:deconz:adapter Payload Buffer: 191300280021000cfef44600e00281f2f1ec92abff8f1363e146beb518c90caba446d4d57207000096ee +23s
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":19,"manufacturerCode":null,"commandIdentifier":0},"Payload":{"options":40,"srcID":4262199329,"frameCounter":3758114548,"commandID":2,"payloadSize":129,"commandFrame":{"raw":{"type":"Buffer","data":[242,241,236,146,171,255,143,19,99,225,70,190,181,24,201,12,171,164,70,212,213,114,7,0,0,150,238]}}},"Command":{"ID":0,"parameters":[{"name":"options","type":33},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGddLink","type":32,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}},"address":4262199329,"endpoint":242,"linkquality":127,"groupID":2948,"wasBroadcast":false,"destinationEndpoint":1}' +26s
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 19 paramId: 5 +6s
  zigbee-herdsman:deconz:adapter Payload Buffer: 191400280021000cfef44600e00281f2f1ec92abff8f1363e146beb518c90caba446d4d57207000095ee +6ms
  zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":20,"manufacturerCode":null,"commandIdentifier":0},"Payload":{"options":40,"srcID":4262199329,"frameCounter":3758114548,"commandID":2,"payloadSize":129,"commandFrame":{"raw":{"type":"Buffer","data":[242,241,236,146,171,255,143,19,99,225,70,190,181,24,201,12,171,164,70,212,213,114,7,0,0,149,238]}}},"Command":{"ID":0,"parameters":[{"name":"options","type":33},{"name":"srcID","type":35,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":0}]},{"name":"gpdIEEEAddr","type":240,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"gpdEndpoint","type":32,"conditions":[{"type":"bitFieldEnum","param":"options","offset":0,"size":3,"value":2}]},{"name":"frameCounter","type":35},{"name":"commandID","type":32},{"name":"payloadSize","type":32},{"name":"commandFrame","type":1009},{"name":"gppNwkAddr","type":33,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]},{"name":"gppGddLink","type":32,"conditions":[{"type":"bitMaskSet","param":"options","mask":16384}]}],"name":"notification"}},"address":4262199329,"endpoint":242,"linkquality":127,"groupID":2948,"wasBroadcast":false,"destinationEndpoint":1}' +3ms
  zigbee-herdsman:deconz:frameParser PANID: 1a62 +6s
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 20 paramId: 5 +5ms
  zigbee-herdsman:deconz:frameParser PANID: 1a62 +4ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 21 paramId: 11 +6ms
  zigbee-herdsman:deconz:frameParser APS_EXT_PANID: 0xdddddddddddddddd +5ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 22 paramId: 11 +4ms
  zigbee-herdsman:deconz:frameParser APS_EXT_PANID: 0xdddddddddddddddd +5ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 23 paramId: 28 +5ms
  zigbee-herdsman:deconz:frameParser CHANNEL: 11 +5ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 24 paramId: 28 +5ms
  zigbee-herdsman:deconz:frameParser CHANNEL: 11 +5ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 25 paramId: 24 +5ms
  zigbee-herdsman:deconz:frameParser NETWORK_KEY: hidden +5ms
  zigbee-herdsman:controller:greenpower Unhandled Zigbee GreenPower command: 0x2 +0ms
  zigbee-herdsman:controller:log 'zcl' data is from unknown device with address '4262199329', skipping... +31ms
  zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 26 paramId: 24 +5ms
  zigbee-herdsman:deconz:frameParser NETWORK_KEY: hidden +5ms
  zigbee-herdsman:controller:greenpower Unhandled Zigbee GreenPower command: 0x2 +5ms
  zigbee-herdsman:controller:log 'zcl' data is from unknown device with address '4262199329', skipping... +4ms
```

**Comment by Koenkk** [comment]
Seems the changes below are enough to make it work again:

Screenshot 2022-05-16 at 17 45 32

**Comment by Koenkk** [comment]
Pushed a temp fix to get it working again: https://github.com/Koenkk/zigbee-herdsman/commit/146997b42dc5b228862cc1057efb8e74be72c556 

I guess this pr is still needed for the powertags.

**Comment by Inrego** [comment]
I have a Conbee II and two PowerTags. If you need me to test anything, let me know.

**Comment by konistehrad** [comment]
Oh gosh in retrospect this makes a certain amount of sense. The existence of `gppIEEEAdr` is predicated on options, but in fact so is `srcID`. In the event that `options & 0b010 == 0b010`, `srcID` is in fact replaced by `gppIEEEAdr`, meaning `srcID` needs to have a condition tag as well. I don't see reference to `gpdEndpoint` in the spec, either, so removing that is also probably the right call. 

image

I'll tuck into some of this today since I'm sick and don't wanna do anything else lol

**Pull request closed without merging**
