### PR TITLE
Add concurrency option 

### PR DESCRIPTION
**Pull request by gev**
Make queue concurrency configurable in the Controller constructor:

```
new Controller({
  databasePath: './some/path/to/db', 
  serialPort: {
    path: '/dev/ttyACM0',
    adapter: 'zstack',
  }, 
  concurrent: 16,
});
```

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Koenkk** [comment]
Added see `adapter_concurrent` here: https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/configuration.md

**Comment by timdonovanuk** [comment]
> Added see `adapter_concurrent` here: https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/configuration.md

But what does it do? Can't find anything in any ticket or PR as to what this feature actually does

**Comment by Koenkk** [comment]
It configures the max concurrent Zigbee requests (e.g. turn on light)

**Pull request merged**
