### PR TITLE
Add greenPowerKey for ZGP devices

### PR DESCRIPTION
**Pull request by fredericseiler**
Issue #398

This PR adds a `greenPowerKey` device attribute, to better identify ZGP devices.

The key is a string built upon some infos from the ZCL data payload when commissioning a new ZGP device, separated by dots (`.`).

`options` `.` `payloadSize` `.` `commandFrame.options` `.` `commandFrame.extendedOptions`

A ZCL payload example:
```json
"Payload": {
    "options": 62149,
    "srcID": ...,
    "frameCounter": ...,
    "commandID": ...,
    "payloadSize": 31,
    "commandFrame": {
        "deviceID": ...,
        "options": 197,
        "extendedOptions": 242,
        "securityKey": ...,
        "keyMic": ...,
        "outgoingCounter": ...
    }
},
```

The corresponding fingerprint for the device definition:
```js
fingerprint: [{
    greenPowerKey: '62149.31.197.242'
}],
```

Note: the key is also present on non-ZGP devices, but with an `null` value.

### CODE REVIEW

**Comment by fredericseiler** [comment]
@Koenkk I'm not quite confident with what I did to store and retrieve the key (`device.ts`). It's working well for ZGP and non-ZGP devices, but I'm not sure that all modifications are needed.

**Comment by Koenkk** [comment]
Made some small changes and looks good to me!

I've updated https://github.com/Koenkk/zigbee-herdsman-converters/pull/2885 with the Hue tap fingerprint, could you also add your green power devices in a similar way?

**Comment by fredericseiler** [comment]
Thanks for the fixes (and tests)!

I'll add my devices in a few moments (I'm testing those with external converters to make sure everything's good).

**Comment by Koenkk** [comment]
big thanks @fredericseiler !

**Pull request merged**
