### PR TITLE
Update cluster.ts

### PR DESCRIPTION
**Pull request by turboproc**
Some further addition to complete the cluster definitions. This PR adds the serialNumber attribute to the genBasic cluster

### CODE REVIEW

**Comment by turboproc** [comment]
Do this again

**Comment by Koenkk** [comment]
Could you update the tests?

**Comment by turboproc** [comment]
Let me discover how the testing part works. Never done that before. Might need a little hint.

**Comment by turboproc** [comment]
Updated test

**Comment by turboproc** [comment]
Removed typo

**Comment by turboproc** [comment]
Some more

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
