### PR TITLE
add JSON serialization for devices, endpoints and groups

### PR DESCRIPTION
**Pull request by hobbyquaker**
Hi Koenkk! I'd like to have the possibility to JSON.stringify these Objects (would be more convenient for me, usecase: user interface) - so my first attempt was to add toJSON() methods (those get automatically applied when using JSON.stringify on the objects). This breaks a bunch of tests... If you would accept this PR I would adapt the tests, just wanted to ask you if that PR makes sense and is acceptable for you before putting effort in adapting the tests.

### CODE REVIEW

**Comment by hobbyquaker** [comment]
Another thing: I'm not sure if I'm messing up the database with this change? Can you point me in the right direction? ;)

**Comment by hobbyquaker** [comment]
More thoughts: How about just renaming the existing toDatabaseRecord methods to toJSON and changing `Entity.database.update(this.toDatabaseRecord());` to `Entity.database.update(this);`

**Comment by Koenkk** [comment]
`toDatabaseRecord` also takes care of the legacy format, this is probably not what you want to see as a library user. 

What about `JSON.stringify(device)`, doesn't that already work?

**Comment by hobbyquaker** [comment]
when I just stringify the device object I get the private properties in the resulting JSON, it's ignoring the getters/accessors. So the change from 0.7 to 0.8 broke my UI and I thought it would be a cleaner solution to use toJSON to utilize the getters instead of adapting the UI to use the underscore-prefixed private properties.

**Comment by Koenkk** [comment]
Somehow I don't feel that this logic should be here; what if you e.g. want to show/hide some properties in your UI in the future?

Logic that converts an object to something useful to be shown on the UI should be part of the UI code and not the library code.

**Comment by hobbyquaker** [comment]
I see your point - but I have also another possible view on that question: Isn't it "unbeautiful" that a JSON stringified device object shows up with properties that are private? Another point is that the getters do not always just hand-through the private properties, at some places they do a transformation that then would be lost in the JSON stringified object.

**Comment by hobbyquaker** [comment]
And another thought: if we don't introduce the toJSON that uses the getters we encourage zigbee-herdsman api consumers to work with private properties and should remove the `excludePrivate` from the typedoc config.

**Comment by Koenkk** [comment]
Instead of a `JSON.stringify(device)` in your code; you should explicitly map the properties you want to show on the UI e.g. `toShow = {networkAddress: device.networkAddress, ieeeAddr: device.ieeeAddr}`

How do we encourage them to use private properties? Private should indeed private; if you make a typescript project based in zigbee-herdsman you should even get a compiler error when accessing private properties.

**Comment by hobbyquaker** [comment]
Ok, then the recommendation for herdsman api consumers is so to say "just don't JSON.stringify a device object directly"?

**Comment by hobbyquaker** [comment]
Implemented it in node-red-contrib-zigbee now: https://github.com/hobbyquaker/node-red-contrib-zigbee/blob/master/lib/json.js
But to be honest: that's fine for me, but I'm still not convinced that this belongs there and not in the herdsman. ;-)

**Pull request closed without merging**
