### PR TITLE
EZSP: Network restore from backup

### PR DESCRIPTION
**Pull request by kirovilya**
I tried to implement the restoration of network parameters from a backup.

### CODE REVIEW

**Comment by Nerivec** [comment]
Last time I looked, I think I saw `Driver.getKey` was exporting the wrong keys for >=13 (`exportKey` doesn't use `EmberKeyType` like the old `getKey`).
Did you double-check?
https://github.com/Koenkk/zigbee-herdsman/blob/795c9446783e7ecd06a1d03e912e09a9e5b01228/src/adapter/ember/enums.ts#L2085

**Comment by kirovilya** [comment]
> Did you double-check?

hmmm. I haven't well checked it on EZSP 13... I'll check it now. Thank you!

**Comment by Koenkk** [comment]
Ready for merge?

**Comment by kirovilya** [comment]
> Ready for merge?

yes

**Comment by Koenkk** [comment]
thanks!

**Pull request merged**
