### PR TITLE
Added ZXZIR-02 (TS1201) commands and responses.

### PR DESCRIPTION
**Pull request by mak-42**
Issue: https://github.com/Koenkk/zigbee2mqtt/issues/11633

### CODE REVIEW

**Comment by Koenkk** [comment]
Can you add the manufacturer code to the added cluster (like https://github.com/Koenkk/zigbee-herdsman/blob/0c606b72b31ec43d05a8127df4e83387020ba025/src/zcl/definition/cluster.ts#L4133) ?

**Comment by mak-42** [comment]
> Can you add the manufacturer code to the added cluster

I've get this information analyzing the captured packets. Could you please point where I can get manufacturer code?

I have a small investigation and figure out that the devices are likely manufactured by Shenzhen Zhuoxing Smart Technology Co., Ltd. (Zosung, [device page](http://www.zosung.cn/en/productshow.asp?Id=263)) for different vendors like AUBESS and so on.

**Comment by Koenkk** [comment]
@mak-42 can you provide a screenshot of the sniff packet with all the panels in the bottom expanded?

**Comment by mak-42** [comment]
Look at one of packets the device sent. 

```
Frame 27: 124 bytes on wire (992 bits), 124 bytes captured (992 bits) on interface \\.\pipe\tiwspc_data, id 0
Internet Protocol Version 4, Src: 192.168.1.3, Dst: 192.168.1.3
User Datagram Protocol, Src Port: 17754, Dst Port: 17754
    Source Port: 17754
    Destination Port: 17754
    Length: 104
    Checksum: 0xffce [unverified]
    [Checksum Status: Unverified]
    [Stream index: 0]
    [Timestamps]
    UDP payload (96 bytes)
ZigBee Encapsulation Protocol, Channel: 11, Length: 64
    Protocol ID String: EX
    Protocol Version: 2
    Type: Data (1)
    Channel ID: 11
    Device ID: 34448
    LQI/CRC Mode: LQI
    Link Quality Indication: 127
    Timestamp: (0)Jan  1, 1970 00:00:00.000000000 UTC
    Sequence Number: 6541
    .100 0000 = Length: 64 bytes
IEEE 802.15.4 Data, Dst: 0x0000, Src: <REDACTED>
    Frame Control Field: 0x8861, Frame Type: Data, Acknowledge Request, PAN ID Compression, Destination Addressing Mode: Short/16-bit, Frame Version: IEEE Std 802.15.4-2003, Source Addressing Mode: Short/16-bit
        .... .... .... .001 = Frame Type: Data (0x1)
        .... .... .... 0... = Security Enabled: False
        .... .... ...0 .... = Frame Pending: False
        .... .... ..1. .... = Acknowledge Request: True
        .... .... .1.. .... = PAN ID Compression: True
        .... .... 0... .... = Reserved: False
        .... ...0 .... .... = Sequence Number Suppression: False
        .... ..0. .... .... = Information Elements Present: False
        .... 10.. .... .... = Destination Addressing Mode: Short/16-bit (0x2)
        ..00 .... .... .... = Frame Version: IEEE Std 802.15.4-2003 (0)
        10.. .... .... .... = Source Addressing Mode: Short/16-bit (0x2)
    Sequence Number: 193
    Destination PAN: 0x606a
    Destination: 0x0000
    Source: <REDACTED>
    [Extended Source: SiliconL_ff:<REDACTED2> (00:3c:84:ff:<REDACTED2>)]
    [Origin: 2]
    TI CC24xx-format metadata: FCS OK
        FCS Valid: True
        RSSI: 24 dB
        LQI Correlation Value: 104
ZigBee Network Layer Data, Dst: 0x0000, Src: <REDACTED>
    Frame Control Field: 0x0248, Frame Type: Data, Discover Route: Enable, Security Data
        .... .... .... ..00 = Frame Type: Data (0x0)
        .... .... ..00 10.. = Protocol Version: 2
        .... .... 01.. .... = Discover Route: Enable (0x1)
        .... ...0 .... .... = Multicast: False
        .... ..1. .... .... = Security: True
        .... .0.. .... .... = Source Route: False
        .... 0... .... .... = Destination: False
        ...0 .... .... .... = Extended Source: False
        ..0. .... .... .... = End Device Initiator: False
    Destination: 0x0000
    Source: <REDACTED>
    Radius: 30
    Sequence Number: 20
    [Extended Source: SiliconL_ff:<REDACTED2> (00:3c:84:ff:<REDACTED2>)]
    [Origin: 2]
    ZigBee Security Header
ZigBee Application Support Layer Data, Dst Endpt: 1, Src Endpt: 1
    Frame Control Field: Data (0x00)
        .... ..00 = Frame Type: Data (0x0)
        .... 00.. = Delivery Mode: Unicast (0x0)
        ..0. .... = Security: False
        .0.. .... = Acknowledgement Request: False
        0... .... = Extended Header: False
    Destination Endpoint: 1
    Cluster: Unknown (0xed00)
    Profile: Home Automation (0x0104)
    Source Endpoint: 1
    Counter: 173
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x01)
        .... ..01 = Frame Type: Cluster-specific (0x1)
        .... .0.. = Manufacturer Specific: False
        .... 0... = Direction: Client to Server
        ...0 .... = Disable Default Response: False
    Sequence Number: 46
    Command: Unknown (0x00)
Data (16 bytes)
    Data: 01002e0000000000000004e001040000
    [Length: 16]
```

**Comment by Koenkk** [comment]
I see `Manufacturer Specific: False` , so no manufacturer codes can be applied to these clusters, thanks for the info!

**Pull request merged**
