### PR TITLE
fix(ignore): remove all ubisys custom cluster/attributes

### PR DESCRIPTION
**Pull request by sjorge**
Merge after https://github.com/Koenkk/zigbee-herdsman-converters/pull/7451

### CODE REVIEW

**Comment by sjorge** [comment]
For the tests, we will probably hit this again once we remove more of those attributes.

**Comment by sjorge** [comment]
Oh boy, this mrege conflict is a big pain I might close and redo this PR from scratch. The tests are the biggest pain as we basically removed all the problem childs from ubisys were we have so many tests for.

**Comment by Koenkk** [comment]
Could you rebase this PR?

**Comment by sjorge** [comment]
> Could you rebase this PR?

I am trying but I'm having a really hard time, the tests are broken again and I am pretty sure I rebased those correctly :/

**Comment by sjorge** [comment]
It seems more tests got added that use ubisys attributes between me opening this one? :/

**Comment by Koenkk** [comment]
In this PR probably: https://github.com/Koenkk/zigbee-herdsman/commit/f88b4d64ed6e96e52b709fa98c7110686e84180c

**Comment by sjorge** [comment]
Seems to have been a miss-rebase with {} being added in some spots

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
