### PR TITLE
mgmtNWKUpdateNotify response

### PR DESCRIPTION
**Pull request by kirovilya**
http://software-dl.ti.com/simplelink/esd/plugins/simplelink_zigbee_sdk_plugin/2.20.00.06/exports/docs/zigbee_user_guide/doxygen/zstackapi/html/struct__zstack__zdomgmtnwkupdatenotifyind__t.html

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, renamed slightly.

What do you plan using this for?

**Comment by kirovilya** [comment]
```
        const payload = {
            dstaddr: 0x0, 
            dstaddrmode: 0x02,
            channelmask: 0x07FFF800,
            scanduration: 0x5,
            scancount: 1,
            nwkmanageraddr: 0x0000
        };
        const energyScan = this.herdsman.adapter.znp.waitFor(
            2, //unpi_1.Constants.Type.AREQ, 
            5, //Subsystem.ZDO, 
            'mgmtNWKUpdateNotify'
        );
        await this.herdsman.adapter.znp.request(
            0x5, //Subsystem.ZDO
            'mgmtNwkUpdateReq',
            payload,
            energyScan.ID
        );
        const result = await energyScan.start().promise;
```
image

**Comment by kirovilya** [comment]
some interesting tools here https://github.com/zha-ng/zigpy-znp

**Comment by Koenkk** [comment]
Interesting!

**Pull request merged**
