### PR TITLE
move recording of bindings to addBinding

### PR DESCRIPTION
**Pull request by sjorge**
@Koenkk this is first stab at it, but I am having issues testing this.

I added tests and the coverage is now OK, but I can't seem to get this branch installed in my z2m install to test if it actually still works,  I did `npm install git://github.com/sjorge/zigbee-herdsman.git#addbinding` but that doesn't seem top generate the nodejs form the typescript?

### CODE REVIEW

**Comment by sjorge** [comment]
Oh good, I can probably just use npm test in the initial stage!

**Comment by sjorge** [comment]
Blarh not sure why coverage is failing, I am hitting the code I moved in the tests.

**Comment by Koenkk** [comment]
To test your changes you (on a bare metal system):
- Go to Z2M dir and execute `cd node_modules && rm -rf zigbee-herdsman`
- Clone the git: `git clone git@github.com:Koenkk/zigbee-herdsman.git` (or a fork)
- Execute `cd zigbee-herdsman && npm ci`
- Change the code (`.ts` files under `src`, not `.js` under `dist`)
- Execute `npm run build` OR as an alternative you can use `npm start`, this will rebuild the code automatically if you make changes, very handy for quick development)
- Start zigbee2mqtt

**Comment by sjorge** [comment]
Ah yes, the npm run build fixes it! z2m is happy to start now and everything still works!

Original (bind to group)
```json
{"id":53,"type":"EndDevice","ieeeAddr":"0x14b457fffeca351b","nwkAddr":44644,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI on/off switch","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2080,"inClusterList":[0,1,3,9,32,4096,64636],"outClusterList":[3,4,6,8,25,258,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI on/off switch","manufacturerName":"IKEA of Sweden","powerSource":3,"zclVersion":3,"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190723","swBuildId":"2.2.010"}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":60}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001938a7e5","endpointID":1},{"cluster":6,"groupID":10112,"type":"group"},{"cluster":8,"groupID":10112,"type":"group"},{"cluster":258,"groupID":10112,"type":"group"}],"meta":{}}},"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190723","swBuildId":"2.2.010","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1,"reporting":1},"lastSeen":1605971423522}
```

Unbind from group
```json
{"id":53,"type":"EndDevice","ieeeAddr":"0x14b457fffeca351b","nwkAddr":44644,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI on/off switch","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2080,"inClusterList":[0,1,3,9,32,4096,64636],"outClusterList":[3,4,6,8,25,258,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI on/off switch","manufacturerName":"IKEA of Sweden","powerSource":3,"zclVersion":3,"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190723","swBuildId":"2.2.010"}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":60}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001938a7e5","endpointID":1}],"meta":{}}},"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190723","swBuildId":"2.2.010","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1,"reporting":1},"lastSeen":1605974632038}
```

Bind to group with updated zigbee-herdsman
```json
{"id":53,"type":"EndDevice","ieeeAddr":"0x14b457fffeca351b","nwkAddr":44644,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI on/off switch","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2080,"inClusterList":[0,1,3,9,32,4096,64636],"outClusterList":[3,4,6,8,25,258,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI on/off switch","manufacturerName":"IKEA of Sweden","powerSource":3,"zclVersion":3,"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190723","swBuildId":"2.2.010"}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":60}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001938a7e5","endpointID":1},{"cluster":8,"groupID":10112,"type":"group"},{"cluster":6,"groupID":10112,"type":"group"}],"meta":{}}},"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190723","swBuildId":"2.2.010","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1,"reporting":1},"lastSeen":1605974828504}
```

I noticed I had closure bound, which I did not rebind, and everything looks correct... the remote works again and the entries are correctly stored in the database.

So I guess this is good to go.

**Comment by Koenkk** [comment]
Thanks, since none of the methods called in `addBinding` are async, this method also does not have to be async.

**Pull request merged**
