### PR TITLE
Update cluster.ts

### PR DESCRIPTION
**Pull request by smarts4home**
New cluster command (240) required by Bosch Siren to start and stop alarm

### CODE REVIEW

**Comment by Multipage** [comment]
@Koenkk , there have been 2 updates of zigbee2mqtt and none of these updates had this fix. When will this be implemented/released ?

**Comment by Koenkk** [comment]
@smarts4home I guess that still a PR to zigbee-herdsman-converters has to be created to implement this feature?

**Comment by smarts4home** [comment]
> @smarts4home I guess that still a PR to zigbee-herdsman-converters has to be created to implement this feature?

I did it before. The only thing I forgot, was new a cluster command.

**Comment by Multipage** [comment]
I've updated 5 minutes ago (the hotfix) it's updated there but not mentioned in the changelog.

It worked! Thanks!

**Pull request merged**
