### PR TITLE
add Controller.setLED method, remove Controller.disableLED

### PR DESCRIPTION
**Pull request by hobbyquaker**

### CODE REVIEW

**Comment by Koenkk** [comment]
I think we should merge the `disableLED` and `enableLED` into one function. 

Something like `setLED(enabled: boolean)`?

**Comment by hobbyquaker** [comment]
makes sense, will do :)

**Comment by Koenkk** [comment]
Great, thanks again!

**Comment by hobbyquaker** [comment]
You're welcome :-)

**Pull request merged**
