### PR TITLE
[WIP] #106  Store lastSeen

### PR DESCRIPTION
**Pull request by sjorge**
@Koenkk I think this should do the trick to store lastSeen... but I'm not sure how to test this?
As I can't just replace the .ts files in my active zigbee2mqtt instance.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks again!

**Comment by sjorge** [comment]
@Koenkk Maybe something is still not OK?

```
zigbee2mqtt:info  2019-12-15 15:50:00: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b001938a7e5","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1576425000298},{"ieeeAddr":"0x000d6ffffe8e8d4f","type":"Router","networkAddress":47816,"model":"E1746","friendly_name":"masterbedroom/repeater","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelID":"TRADFRI signal repeater","hardwareVersion":1,"softwareBuildID":"2.0.019","dateCode":"20180828","lastSeen":null},{"ieeeAddr":"0x90fd9ffffee77fcf","type":"Router","networkAddress":48533,"model":"LED1624G9","friendly_name":"bedroom/night_light/bulb","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelID":"TRADFRI bulb E27 CWS opal 600lm","hardwareVersion":1,"softwareBuildID":"1.3.009","dateCode":"20180410","lastSeen":null},{"ieeeAddr":"0x0017880104259333","type":"Router","networkAddress":27321,"model":"9290012573A","friendly_name":"bedroom/desk_lamp/bulb","manufacturerID":4107,"manufacturerName":"Philips","powerSource":"Mains (single phase)","modelID":"LCT012","hardwareVersion":1,"softwareBuildID":"1.29.0_r21169","dateCode":"20170908","lastSeen":null},{"ieeeAddr":"0x14b457fffecc1315","type":"EndDevice","networkAddress":44663,"model":"E1743","friendly_name":"bedroom/night_light/remote","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","modelID":"TRADFRI on/off switch","hardwareVersion":1,"softwareBuildID":"2.2.008","dateCode":"20190410","lastSeen":null},{"ieeeAddr":"0x14b457fffeca351b","type":"EndDevice","networkAddress":26399,"model":"E1743","friendly_name":"bedroom/desk_lamp/remote","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","modelID":"TRADFRI on/off switch","hardwareVersion":1,"softwareBuildID":"2.2.008","dateCode":"20190410","lastSeen":null},{"ieeeAddr":"0x00158d0004148f89","type":"EndDevice","networkAddress":4263,"model":"RTCGQ11LM","friendly_name":"bedroom/motion","manufacturerID":4151,"manufacturerName":"LUMI","powerSource":"Battery","modelID":"lumi.sensor_motion.aq2","lastSeen":null},{"ieeeAddr":"0x00158d00033ddfaa","type":"EndDevice","networkAddress":28407,"model":"WSDCGQ11LM","friendly_name":"bedroom/sensor","manufacturerID":4151,"manufacturerName":"LUMI","powerSource":"Battery","modelID":"lumi.weather","hardwareVersion":30,"softwareBuildID":"3000-0001","dateCode":"20161129","lastSeen":null},{"ieeeAddr":"0x00158d0003f115c5","type":"EndDevice","networkAddress":23324,"model":"WSDCGQ11LM","friendly_name":"serverroom/sensor","manufacturerID":4151,"manufacturerName":"LUMI","powerSource":"Battery","modelID":"lumi.weather","hardwareVersion":30,"softwareBuildID":"3000-0001","dateCode":"20161129","lastSeen":null},{"ieeeAddr":"0x00158d0001ffaffc","type":"EndDevice","networkAddress":49490,"model":"SPZB0001","friendly_name":"bedroom/radiator","manufacturerID":4151,"manufacturerName":"Eurotronic","powerSource":"Battery","modelID":"SPZB0001","hardwareVersion":35,"softwareBuildID":"22190930","dateCode":"20191014","lastSeen":null}]}'
```

I would not expect those nulls to be there as most (all) devices had checked in atleast once before I stopped and started zigbee2mqtt.

**Comment by Koenkk** [comment]
Can you force that device to send a message, check if it has last seen, restart zigbee2mqtt, check if it still has last seen?

**Comment by sjorge** [comment]
For both the Aqara motion and Ikea on/off remotes this is easy to do... 

```
zigbee2mqtt:debug 2019-12-15 16:45:36: Received Zigbee message from 'bedroom/motion', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":0}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2019-12-15 16:45:36: Received Zigbee message from 'bedroom/motion', type 'attributeReport', cluster 'msOccupancySensing', data '{"occupancy":1}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2019-12-15 16:45:37: MQTT publish: topic 'zigbee2mqtt/bedroom/motion', payload '{"battery":100,"voltage":3015,"illuminance":0,"linkquality":39,"occupancy":true}'
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/masterbedroom/repeater/availability', payload 'offline'
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/bedroom/night_light/bulb/availability', payload 'offline'
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/bedroom/desk_lamp/bulb/availability', payload 'offline'
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/bedroom/night_light/remote/availability', payload 'offline'
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/bedroom/desk_lamp/remote/availability', payload 'offline'
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/bedroom/motion/availability', payload 'offline'
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/bedroom/sensor/availability', payload 'offline'
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/serverroom/sensor/availability', payload 'offline'
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/bedroom/radiator/availability', payload 'offline'
zigbee2mqtt:debug 2019-12-15 16:45:55: Saving state to file /opt/zigbee2mqtt/data/state.json
zigbee2mqtt:info  2019-12-15 16:45:55: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
zigbee2mqtt:info  2019-12-15 16:45:55: Disconnecting from MQTT server
zigbee2mqtt:info  2019-12-15 16:45:55: zigbee-herdsman stopped
```

At this state it should have a lastSeen... 

```
[root@amethyst /opt/zigbee2mqtt]# grep 0x00158d0004148f89 data/database.db
{"id":10,"type":"EndDevice","ieeeAddr":"0x00158d0004148f89","nwkAddr":4263,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion.aq2","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"65281":{"1":3015,"3":26,"4":5032,"5":39,"6":[0,131085],"10":27321,"11":3,"100":0},"modelId":"lumi.sensor_motion.aq2","appVersion":5}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":0}},"msOccupancySensing":{"attributes":{"occupancy":1}}},"binds":[]}},"appVersion":5,"interviewCompleted":true,"meta":{}}
```

Doesn't look like it got saved...

**Comment by Koenkk** [comment]
Are you sure you are on the latest dev and did `rm -rf node_modules && npm install` afterwards? It works fine in my case, even when the device didn't send something you should see `"lastSeen": null` in the database.db after stopping zigbee2mqtt.

**Comment by sjorge** [comment]
seems ok on 1.8.0+dev, I was still on 1.7.0+dev from 2 days ago

**Comment by qm3ster** [comment]
> As I can't just replace the .ts files in my active zigbee2mqtt instance.

@sjorge you could mount `/lib/` into your container, then you would not have to rebuild the entire container to do changes.
For example, to run a container that will get deleted when you stop it, and where you are dropped into a shell so you can restart zigbee2mqtt as many times as you want with `./run.sh`:
```sh
docker run -rm \
  --name zigbee2mqtt-development \
  --device /dev/serial/by-id/usb-Texas_Instruments_XDS110__02.03.00.18__Embed_with_CMSIS-DAP_L11009C5-if00:/dev/ttyACM0 \
  -v /home/rock64/house/zigbee2mqtt:/app/data \
  -v /home/rock64/development/zigbee2mqtt/lib:/app/lib \
  -e "TZ=Asia/Nicosia" \
  --entrypoint=/bin/sh
  koenkk/zigbee2mqtt
```

**Pull request merged**
