### PR TITLE
[WIP]: EFR32 EmberZNet EZSP adapter

### PR DESCRIPTION
**Pull request by kirovilya**
The adapter is designed to work with EFR32 chips using the EmberZNet v8 protocol. Recommended firmware NCP 6.7.8.

The work with devices with such chips was tested:
* Re-flashed Sonoff Zigbee Bridge gateway https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html
* Flashed devboard EByte E180-ZG120B https://github.com/zigpy/zigpy/discussions/584
* Flashed usb stick based on SM-011 https://modkam.ru/?p=1889 (description in Russian, use the translator)
* Defaro Sprut stick https://spruthub.ru/device/defaro-sprut-stick-2-pro (description in Russian, use the translator)

Settings:
* specify **port** parameter or gateway address
* set **adapter** to "ezsp"

Worked:

- [X] Pairing/Leaving
- [X] Bind/Unbind
- [X] ZCL messages/commands
- [X] Network map

TODO:

- [ ] Improving the stability work of the network
- [ ] Groups
- [ ] Touchlink 
- [ ] Backup/Restore
- [ ] OTA update
- [ ] Tests
- [ ] ZGP (Zigbee Green Power)

I urge the developers to participate in the finalization of the adapter. I'm not an expert in TypeScript and EmberZNet, so I ask for help.

p.s. Special thanks to @G1K for help with development

### CODE REVIEW

**Comment by MattWestb** [comment]
For compatible radio adapter with EZSP version 6.7.8.0 i have doing one matrix showing wot we have getting working and pending and no respond on request for updating coordinator firmware (= No interest from devs). https://github.com/zigpy/zigpy/discussions/636#discussion-1925478

 EZSP version 6.7.0.0 is the lowest working with protocol version 8 so if you is having 6.5.1.0 its not working with this implantation !!

Our (ZHA) firmware cooker is for the moment **NOT** recommending  higher then versions of EZSP 6.7.8.0 then some critical bugs ("The Sonoff bug") is not fixed and new is implanted in the 6.8 and 6.9 branch.

Great work done devs and hop more great thing is coming soon !!!

**Comment by kirovilya** [comment]
@MattWestb Great, thanks for the info! I've looked a lot at your Zigpy / Bellows work on EZSP implementation

**Comment by MattWestb** [comment]
Tasmota is new made and is supporting only protocol version 8 so its easier seeing wot the devs have being doing but bellows is having more functionality implanted and better security implanted.

Keep coding well so we soon can running our EFR32 and EM35X on Z2M !!

**Comment by Hedda** [comment]
@kirovilya If this adapter specifically use "EmberZNet Serial Protocol" interface (similarly to [bellows](https://github.com/zigpy/bellows) for zigpy) then I suggest that you call the zigbee-herdsman adapter for "EZSP" instead of calling the adapter for "EmberZNet" to prevent possible future confusion? 

The reason for that is that "EmberZNet" is also the generic name for the Zigbee stack from Silicon Labs and a developer could technically create an EmberZNet application firmware for Silabs hardware that has another API or CLI interface that is not EZSP.

In fact, Telegesis ETRX3 series modules are based on Silabs hardware with EmberZNet application firmware but have an AT-command interface instead as standard, (though you can flash them yourself with alternative firmware that features the EZSP interface).

https://www.silabs.com/wireless/zigbee/telegesis-legacy-modules

https://www.silabs.com/documents/public/reference-manuals/TG-ETRXn-Commands.pdf

https://www.silabs.com/documents/public/data-sheets/TG-PM-0516-ETRX35x.pdf

PS: @grobasoz also mentioned that he has been thinking about creating an EmberZNet application firmware  for Silabs hardware that would be compatible with standard Z-Stack interface so even could use the (unmodified) z-stack adapter for zigbee-herdsman

**Comment by kirovilya** [comment]
@Hedda I named the adapter is "EZSP", just in the title of this PR I indicated EmberZNet. I can rename the title of PR if necessary :) I think this is not critical

**Comment by MattWestb** [comment]
Then in implantation is only supporting EZSP v8 and not older version of EmberZNet i thik its one god working name and also as "end name" and the devs dont have any intention to supporting old "AT firmware" and the firmware requirements is already being sett = the same as "ZHA EZSP PRO".

**Comment by Hedda** [comment]
> For compatible radio adapter with EZSP version 6.7.8.0 i have doing one matrix showing wot we have getting working and pending and no respond on request for updating coordinator firmware (= No interest from devs). [zigpy/zigpy#636 (comment)](https://github.com/zigpy/zigpy/discussions/636#discussion-1925478)

Direct link to the wiki page where @MattWestb documented recommended application firmware version for EZSP Coordinators:

https://github.com/zigpy/zigpy/wiki/Coordinator-Firmware-Updates#recommended-firmware-version-for-ezsp-coordinators

Perhaps also good to mention that @walthowd created a docker image that can help upgrade firmware on most EFR32 hardware:

https://github.com/walthowd/husbzb-firmware

That includes but is not exclusive to the popular but no longer manufactured Nortek GoControl QuickStick Combo Model HUSBZB-1

**Comment by Hedda** [comment]
> Then in implantation is only supporting EZSP v8 and not older version of EmberZNet i thik its one god working name and also as "end name" and the devs dont have any intention to supporting old "AT firmware" and the firmware requirements is already being sett = the same as "ZHA EZSP PRO".

Bellows also started out only supporting a single specific version of EZSP but it was later extended to support more versions.

So while this new adapter will start out only supporting EZSP v8 it could maybe be extended by someone else in the future, though that effort might not be worth it in the end. Perhaps most important to know today is that EZSP v5, v6 and v7 (EmberZNet 6.6.x.x) use the same framing format, but EmberZNet 6.7.x.x/EZSP v8 introduced new framing format and expanded command id field from 8 bits to 16 bits.

**Comment by digiblur** [comment]
Awesome work!  Looking forward to checking this out.  I do have this one to also try out for testing from iTead - 
image

**Comment by digiblur** [comment]
@kirovilya I'll definitely be keeping an eye on this and see where I can help out, the previous bounty offer still stands in my book.

**Comment by Hedda** [comment]
Another item for TODO could be "ZGP (Zigbee Green Power)" support for EmberZNet/EZSP adapter:

https://www.silabs.com/documents/public/user-guides/ug392-using-sl-green-power-with-ezp.pdf

https://www.silabs.com/documents/public/user-guides/ug103-15-green-power-fundamentals.pdf

By the way, @G1K also has "GreenPower support and 242 endpoint" on his ZiGate roadmap in https://github.com/Koenkk/zigbee-herdsman/issues/242

**Comment by kirovilya** [comment]
@digiblur :) ok, thanks
@Hedda added

**Comment by kirovilya** [comment]
Now, you can try to test it in dev-version of z2m

**Comment by digiblur** [comment]
Paired up a Sonoff Zigbee Mini switch with the Sonoff Zigbee Bridge and was able to turn it on and off.

**Comment by digiblur** [comment]
Weird... I tried to remove it from the bridge, then changed my dev container to the USB dongle and it starts up but failed on pairing 2 devices.  I switched back to the bridge and it fails as well.  I'll have to investigate later when I have more time to fool with it.

**Comment by digiblur** [comment]
Fiddling and messing with it, got the bridge working again after dumped all the settings.  I'll see if I can get the stick working again, I want to see if one mains and one battery powered will stay alive for a bit.

**Comment by digiblur** [comment]
Works on the MG21 based Zigbee Dongle 3.0.  Nice job!  Definitely some issues with the devices hanging on between networks, changing the network keys fixes that when I switch adapters and pair stuff again.  It's showing  6.7.8.0 build 373

**Comment by kirovilya** [comment]
made a separate issue for further improvements, cause this PR is already merged https://github.com/Koenkk/zigbee-herdsman/issues/319

**Comment by Arkdor** [comment]
Hi, i have Sonoff ZbBridge flashed with Tasmota how can I add it to Zigbee2MQTT? I setup port to 192.168.1.7:8888 and it cannot connect.

**Comment by kirovilya** [comment]
@Arkdor did you setup dev-branch of z2m? In configuration set adapter to ezsp?

**Comment by Arkdor** [comment]
Im using edge version in homeassistant, adapter set to ezsp

**Comment by digiblur** [comment]
> Im using edge version in homeassistant, adapter set to ezsp. In zha port connection looks like this: socket://192.168.1.7:8888, how should it look in z2m?

https://www.digiblur.com/2021/03/zigbee2mqtt-with-sonoff-zigbee-bridge.html

**Comment by Hedda** [comment]
> > Im using edge version in homeassistant, adapter set to ezsp. In zha port connection looks like this: socket://192.168.1.7:8888, how should it look in z2m?
> 
> https://www.digiblur.com/2021/03/zigbee2mqtt-with-sonoff-zigbee-bridge.html

Note! EmberZNet USB Zigbee adapters/dongles/sticks are highly recommended instead of using a remotely connected Ember module over a serial-to-ip bridge / serial forwarding server like ser2net, but if you still insist on using a remotely connected Ember module over a serial-to-ip bridge then the recommendation is to use a model that features wired Ethernet instead of WiFi.

FYI, Home Assistant ZHA and zigpy developers are now strongly recommending not to use any WiFi based EZSP bridges/gateways.

https://github.com/zigpy/bellows#warning-about-zigbee-to-wifi-bridges

The reason Ember remote bridges over serial-to-IP proxy server is not recommended is that clients using the EZSP serial protocol requires a robust connection between the EmberZNet Zigbee stack running on EFR32 MCU and the serial port of the Zigbee radio. With solutions such as *ITEAD Sonoff ZBBridge* or a Ser2Net serial proxy connection over a WiFi network it is expected to see `NCP entered failed state. Requesting APP controller restart` in the logs. This is a normal part of the operation and indicates there was a drop in communication which caused packet loss to occurred between the zigpy radio library and the Zigbee radio. The use of serial network proxies/bridges/servers over WiFi is therefore not recommended when wanting a stable Zigbee environment with Silicon Labs Ember based Zigbee radios. The developers of the [bellows radio library for the zigpy project](https://github.com/zigpy/bellows) has more information about this if needed.

**Comment by Hedda** [comment]
@Arkdor This pull request has been closed so please instead post in the still open issue for improvement discussions ->  https://github.com/Koenkk/zigbee-herdsman/issues/319

**Comment by Hedda** [comment]
FYI, Home Assistant just announced a crowdfunding campaign for official hardware with an onboard/integrated Silicon Labs EFR32MG21/MGM210P Zigbee module with preflashed EZSP compatible firmware:

https://www.home-assistant.io/blog/2021/09/13/home-assistant-amber/

https://www.crowdsupply.com/nabu-casa/home-assistant-amber

https://www.youtube.com/watch?v=KPR-shzT_VQ

**Review by DARKo6o6o6 — APPROVED** [review]

**Review by Zidane115 — COMMENTED** [review]
WWE

**Pull request merged**
