### PR TITLE
Added Sonoff manufacturer's Cluster attribute command definition.

### PR DESCRIPTION
**Pull request by liubotongs**
Added a definition for CommandID:0x01 in the Sonoff manufacturer's Cluster, which is used to set the point function of ZBMicro devices. We will be using zigbee-herdsman-converters.

### CODE REVIEW

**Comment by Nerivec** [comment]
Re https://github.com/Koenkk/zigbee-herdsman/pull/955

**Comment by liubotongs** [comment]
So do we need to change "manuSpecificSonoff" to "manuSpecificEwelink"?

**Comment by Nerivec** [comment]
The same cluster ID is used by multiple manufacturers. This needs the cluster injection feature before it can be added; which is still a work in progress.

**Comment by liubotongs** [comment]
Thank you for your reply. When can we finish the work?

**Comment by Koenkk** [comment]
Implementing it in https://github.com/Koenkk/zigbee-herdsman/pull/1019

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/7432

**Pull request closed without merging**
